# Configuración de la base de datos
spring:
  datasource:
    url: jdbc:mysql://${HOST}/${METRO_DATABASE}
    username: ${USER_DATABASE}
    password: ${PASS_DATABASE}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update