# Configuración de la base de datos
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/metroCard
    username: root
    password: root##root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update