# Configuración de la base de datos
spring:
  datasource:
    url: jdbc:mysql://${HOST}/${METRO_DATABASE}
    username: ${USER_DATABASE}
    password: ${PASS_DATABASE}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: giancarlosleandro1@gmail.com
    password: lcbvatnxfejmnfkd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
